@startuml packages_icenet
set namespaceSeparator none
package "icenet" as icenet #77AADD {
}
package "icenet.cli" as icenet.cli #77AADD {
}
package "icenet.data" as icenet.data #99DDFF {
}
package "icenet.data.datasets" as icenet.data.datasets #99DDFF {
}
package "icenet.data.datasets.splitting" as icenet.data.datasets.splitting #99DDFF {
}
package "icenet.data.datasets.utils" as icenet.data.datasets.utils #99DDFF {
}
package "icenet.data.loader" as icenet.data.loader #99DDFF {
}
package "icenet.data.loaders" as icenet.data.loaders #99DDFF {
}
package "icenet.data.loaders.base" as icenet.data.loaders.base #99DDFF {
}
package "icenet.data.loaders.dask" as icenet.data.loaders.dask #99DDFF {
}
package "icenet.data.loaders.stdlib" as icenet.data.loaders.stdlib #99DDFF {
}
package "icenet.data.loaders.utils" as icenet.data.loaders.utils #99DDFF {
}
package "icenet.data.masks" as icenet.data.masks #99DDFF {
}
package "icenet.data.masks.nsidc" as icenet.data.masks.nsidc #99DDFF {
}
package "icenet.data.masks.osisaf" as icenet.data.masks.osisaf #99DDFF {
}
package "icenet.data.meta" as icenet.data.meta #99DDFF {
}
package "icenet.data.network_dataset" as icenet.data.network_dataset #99DDFF {
}
package "icenet.data.processors" as icenet.data.processors #99DDFF {
}
package "icenet.data.processors.amsr" as icenet.data.processors.amsr #99DDFF {
}
package "icenet.data.processors.cds" as icenet.data.processors.cds #99DDFF {
}
package "icenet.data.processors.cmip" as icenet.data.processors.cmip #99DDFF {
}
package "icenet.data.processors.osisaf" as icenet.data.processors.osisaf #99DDFF {
}
package "icenet.data.references" as icenet.data.references #99DDFF {
}
package "icenet.data.references.osisaf" as icenet.data.references.osisaf #99DDFF {
}
package "icenet.exceptions" as icenet.exceptions #77AADD {
}
package "icenet.model" as icenet.model #44BB99 {
}
package "icenet.model.callbacks" as icenet.model.callbacks #44BB99 {
}
package "icenet.model.cli" as icenet.model.cli #44BB99 {
}
package "icenet.model.handlers" as icenet.model.handlers #44BB99 {
}
package "icenet.model.handlers.wandb" as icenet.model.handlers.wandb #44BB99 {
}
package "icenet.model.losses" as icenet.model.losses #44BB99 {
}
package "icenet.model.metrics" as icenet.model.metrics #44BB99 {
}
package "icenet.model.networks" as icenet.model.networks #44BB99 {
}
package "icenet.model.networks.base" as icenet.model.networks.base #44BB99 {
}
package "icenet.model.networks.tensorflow" as icenet.model.networks.tensorflow #44BB99 {
}
package "icenet.model.predict" as icenet.model.predict #44BB99 {
}
package "icenet.model.train" as icenet.model.train #44BB99 {
}
package "icenet.model.utils" as icenet.model.utils #44BB99 {
}
package "icenet.plotting" as icenet.plotting #BBCC33 {
}
package "icenet.plotting.data" as icenet.plotting.data #BBCC33 {
}
package "icenet.plotting.forecast" as icenet.plotting.forecast #BBCC33 {
}
package "icenet.plotting.trend" as icenet.plotting.trend #BBCC33 {
}
package "icenet.plotting.utils" as icenet.plotting.utils #BBCC33 {
}
package "icenet.plotting.video" as icenet.plotting.video #BBCC33 {
}
package "icenet.process" as icenet.process #AAAA00 {
}
package "icenet.process.azure" as icenet.process.azure #AAAA00 {
}
package "icenet.process.forecasts" as icenet.process.forecasts #AAAA00 {
}
package "icenet.process.local" as icenet.process.local #AAAA00 {
}
package "icenet.process.predict" as icenet.process.predict #AAAA00 {
}
package "icenet.process.train" as icenet.process.train #AAAA00 {
}
package "icenet.process.utils" as icenet.process.utils #AAAA00 {
}
package "icenet.results" as icenet.results #EEDD88 {
}
package "icenet.results.metrics" as icenet.results.metrics #EEDD88 {
}
package "icenet.results.threshold" as icenet.results.threshold #EEDD88 {
}
package "icenet.tests" as icenet.tests #EE8866 {
}
package "icenet.tests.test_entry_points" as icenet.tests.test_entry_points #EE8866 {
}
package "icenet.tests.test_mod" as icenet.tests.test_mod #EE8866 {
}
package "icenet.utils" as icenet.utils #77AADD {
}
icenet.data.datasets.splitting --> icenet.data.datasets.utils
icenet.data.loader --> icenet.data.loaders
icenet.data.loader --> icenet.utils
icenet.data.loaders --> icenet.data.loaders.base
icenet.data.loaders --> icenet.data.loaders.dask
icenet.data.loaders.dask --> icenet.data.loaders.base
icenet.data.loaders.dask --> icenet.data.loaders.utils
icenet.data.loaders.dask --> icenet.data.masks.osisaf
icenet.data.loaders.stdlib --> icenet.data.loaders.base
icenet.data.masks.nsidc --> icenet.utils
icenet.data.meta --> icenet.data.masks.osisaf
icenet.data.network_dataset --> icenet.data.datasets.splitting
icenet.data.network_dataset --> icenet.data.loader
icenet.data.network_dataset --> icenet.utils
icenet.model.cli --> icenet.utils
icenet.model.networks.tensorflow --> icenet.model.networks.base
icenet.model.networks.tensorflow --> icenet.model.utils
icenet.model.predict --> icenet.data.loader
icenet.model.predict --> icenet.data.network_dataset
icenet.model.predict --> icenet.model.cli
icenet.model.train --> icenet.data.network_dataset
icenet.model.train --> icenet.model.cli
icenet.model.train --> icenet.model.handlers.wandb
icenet.model.train --> icenet.model.losses
icenet.model.train --> icenet.model.metrics
icenet.model.train --> icenet.model.networks.tensorflow
icenet.plotting.data --> icenet.data.datasets.utils
icenet.plotting.data --> icenet.data.network_dataset
icenet.plotting.data --> icenet.utils
icenet.plotting.forecast --> icenet
icenet.plotting.forecast --> icenet.cli
icenet.plotting.forecast --> icenet.plotting.utils
icenet.plotting.forecast --> icenet.plotting.video
icenet.plotting.video --> icenet.process.predict
icenet.plotting.video --> icenet.utils
icenet.process.azure --> icenet.process.utils
icenet.process.azure --> icenet.utils
icenet.process.forecasts --> icenet.plotting.utils
icenet.process.forecasts --> icenet.process.utils
icenet.process.forecasts --> icenet.utils
icenet.process.local --> icenet.process.utils
icenet.process.local --> icenet.utils
icenet.process.predict --> icenet
icenet.process.predict --> icenet.data.masks.osisaf
icenet.process.predict --> icenet.data.network_dataset
icenet.process.predict --> icenet.utils
icenet.results.threshold --> icenet.data
icenet.results.threshold --> icenet.utils
@enduml
